# Generated by Django 4.2.20 on 2025-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ser', models.CharField(max_length=255)),
                ('content_ser', models.TextField()),
                ('type_ser', models.CharField(max_length=255)),
                ('price_ser', models.IntegerField()),
                ('is_published_ser', models.BooleanField(default=True)),
            ],
        ),
    ]
