# Generated by Django 4.2.20 on 2025-04-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteProlab', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_m', models.CharField(max_length=255, verbose_name='Должность')),
                ('full_name_m', models.CharField(max_length=255, verbose_name='ФИО')),
                ('studio_m', models.CharField(max_length=255, verbose_name='Студия')),
                ('content_m', models.TextField(verbose_name='Контент о мастере')),
                ('image_m', models.ImageField(upload_to='masters/', verbose_name='Фото мастера')),
                ('services', models.ManyToManyField(to='siteProlab.services', verbose_name='Услуги мастера')),
            ],
        ),
    ]
