# Generated by Django 4.2.20 on 2025-04-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteProlab', '0004_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id']},
        ),
    ]
